In [22]:
import os
import pandas as pd
import pickle as pkl

model_path = r"D:\ML_LEARNING\ML_PROJECTS\Indian_Railways_Failure_Prediction\artifacts\data_preprocessing.pkl"

with open(model_path,'rb') as f:
    model = pkl.load(f)

model.get_feature_names_out()

d:\ML_LEARNING\LLM_LEARNING\Updated_Langchain\.venv\lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator KNNImputer from version 1.9.0 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
d:\ML_LEARNING\LLM_LEARNING\Updated_Langchain\.venv\lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.9.0 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
d:\ML_LEARNING\LLM_LEARNING\Updated_Langchain\.venv\lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.9.0 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

NotImplementedError: (<StringDtype(storage='python', na_value=nan)>, array(['train_id', 'train_age_years', 'average_speed_kmph',
       'distance_travelled_km', 'ambient_temperature_c',
       'humidity_percent', 'rainfall_mm', 'wheel_wear_percent',
       'track_vibration_level', 'rail_wear_mm', 'bearing_temperature_c',
       'axle_temperature_c', 'brake_pad_wear_percent',
       'brake_pressure_psi', 'battery_voltage', 'last_maintenance_days',
       'sensor_health_index', 'inspection_score', 'delay_minutes'],
      dtype=object))

In [2]:
import pandas as pd
df = pd.read_csv(r'D:\ML_LEARNING\ML_PROJECTS\Indian_Railways_Failure_Prediction\artifacts\train_dataset.csv')

In [3]:
df.head()

,train_id,region,season,train_type,train_age_years,average_speed_kmph,distance_travelled_km,ambient_temperature_c,humidity_percent,rainfall_mm,...,brake_pressure_psi,battery_voltage,last_maintenance_days,sensor_health_index,inspection_score,delay_minutes,failure_type,maintenance_required,failure_severity,risk_score
0,76514,Central Railway,Winter,Passenger,9,62.393712,67123,22.8,34.5,NaN,...,102.8,26.20,334,31.3,40.0,16.2,NaN,0,NaN,90.4
1,60407,Southern Railway,Summer,Express,28,107.434499,287297,41.4,52.1,28.6,...,69.5,27.18,275,48.9,54.2,3.4,NaN,0,NaN,88.7
2,27323,South Central Railway,Monsoon,Metro,13,46.446730,441985,25.6,88.6,104.9,...,103.1,22.60,112,68.3,65.0,15.6,Brake Failure,1,Low,74.8
3,53700,Southern Railway,Summer,Freight,1,73.082896,24435,45.5,56.9,1.5,...,131.3,NaN,256,48.9,63.6,14.1,Track Defect,1,Low,65.4
4,65413,Eastern Railway,Summer,Passenger,2,67.962021,145661,38.3,35.1,6.8,...,114.6,26.00,301,26.5,42.9,13.5,NaN,0,NaN,79.5

In [7]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [8]:
df.head()

,train_id,region,season,train_type,train_age_years,average_speed_kmph,distance_travelled_km,ambient_temperature_c,humidity_percent,rainfall_mm,wheel_wear_percent,track_vibration_level,rail_wear_mm,bearing_temperature_c,axle_temperature_c,brake_pad_wear_percent,brake_pressure_psi,battery_voltage,last_maintenance_days,sensor_health_index,inspection_score,delay_minutes,failure_type,maintenance_required,failure_severity,risk_score
0,76514,Central Railway,Winter,Passenger,9,62.393712,67123,22.8,34.5,NaN,39.9,3.31,6.68,NaN,78.9,38.9,102.8,26.20,334,31.3,40.0,16.2,NaN,0,NaN,90.4
1,60407,Southern Railway,Summer,Express,28,107.434499,287297,41.4,52.1,28.6,58.7,4.16,10.40,70.0,71.6,69.0,69.5,27.18,275,48.9,54.2,3.4,NaN,0,NaN,88.7
2,27323,South Central Railway,Monsoon,Metro,13,46.446730,441985,25.6,88.6,104.9,68.7,4.74,8.37,90.7,68.2,27.4,103.1,22.60,112,68.3,65.0,15.6,Brake Failure,1,Low,74.8
3,53700,Southern Railway,Summer,Freight,1,73.082896,24435,45.5,56.9,1.5,22.0,2.48,17.72,66.2,51.4,0.0,131.3,NaN,256,48.9,63.6,14.1,Track Defect,1,Low,65.4
4,65413,Eastern Railway,Summer,Passenger,2,67.962021,145661,38.3,35.1,6.8,13.6,0.55,2.13,70.2,41.1,8.0,114.6,26.00,301,26.5,42.9,13.5,NaN,0,NaN,79.5